planner_frequency: 2.0

TrajectoryPlannerROS:
  max_vel_x: 0.30
  min_vel_x: 0.05
  max_rotational_vel: 0.30
  min_in_place_rotational_vel: 0.01
  min_in_place_vel_theta: 0.01
  max_vel_theta: 0.15
  min_vel_theta: -0.15
  acc_lim_th: 3.2
  acc_lim_x: 10.0
  acc_lim_y: 10.0

  holonomic_robot: false
  
  pdist_scale: 0.9
  #weight for global plan(max 5.0)

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15
