local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false

  rolling_window: true
  #used to keep the costmap centered on the robot when it's moving around

  width: 4.0
  height: 4.0
  resolution: 0.01
  #the dimensions and the resolution of the costmap

  tranform_tolerance: 1.0
  #maximum latency for the transforms(in seconds)

  planner_frequency: 2.0
  #the rate(in Hz) at which to run the planning loop

  planner_patience: 5.0
  #how long the planner will wait(in seconds) in an attempt to find a valid plan, 
  #before space-clearing operations are performed

  plugins:
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}
