footprint: [[1.75, -0.8], [1.75, 0.8], [-1.25, 0.8], [-1.25, -0.8]]
obstacle_range: 15.0
raytrace_range: 16.0

obstacle_layer:
  enabled: true
  observation_sources: scan
  track_unknown_space: false
  
  scan: {
    sensor_frame: base_link,
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true
  }

inflation_layer:
  enabled:              true
  cost_scaling_factor:  0.0
  inflation_radius:     0.2

