global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 10.0 #5
  resolution: 0.02
  inflation_radius: 0.25

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
  
  static_map:
    static_map: true

