gmapping:
  map_udpate_interval: 2.0 #maximum usable range of the laser
  maxUrange: 28.0 #maximum usable range of the laser
  maxRange: 30.0
  linearUpdate: 0.2 #Process a scan each time the robot translates this far
  angularUpdate: 0.1 #Process a scan each time the robot rotates this far
  temporalUpdate: 3.0
  particles: 100
  delta: 0.02 #resolution of map
