local_costmap:
  global_frame: odom
  #map_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 15.0
  height: 15.0
  resolution: 0.02
  footprint_padding: 0.0

  plugins:
    - {name: obstacles_layer,        type: "costmap_2d::ObstacleLayer" }
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer" }
    
  inflation_layer:
    enabled: true
    cost_scaling_factor: 0.0
    inflation_radius: 0.1
