controller_frequency: 5.0
planner_patience: 5.0
controller_patience: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: false
shutdown_costmaps: false
oscillation_timeout: 5.0
oscillation_distance: 0.5
planner_frequency: 0.0
footprint_padding value: 0.01
