yolo_model:

  config_file:
    name: yolov3.cfg
  weight_file:
    name: yolov3.weights
  threshold:
    value: 0.3
  image_view:
    enable_opencv: true
    use_darknet: true
    wait_key_delay: 1
  detection_classes:
    names:
      - blue_cone
      - yellow_cone
      - orange_cone
      - big_orange_cone
